# Generated by Django 4.2 on 2023-04-21 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["-borrow_date"]},
        ),
    ]
