# Generated by Django 4.2 on 2023-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0004_alter_payment_borrowing_alter_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
