# Generated by Django 4.2 on 2023-05-03 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0005_alter_payment_session_id_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-id"]},
        ),
    ]
