# Generated by Django 4.2 on 2023-05-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                check=models.Q(("daily_fee__gte", 0)),
                name="daily_fee_gte_0",
                violation_error_message="Borrowing cost cannot be less than zero",
            ),
        ),
    ]
