# Generated by Django 4.2 on 2023-04-20 07:31

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[book.models.validate_daily_fee],
            ),
        ),
    ]
